[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "GqG5WCUCVhTus2kCXDZLo9AQr6qjG7MnYoiV9dDAoetj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
